"""Auto-fix: open a GitHub pull request that bumps vulnerable dependencies.

Safety model:
- Requires a GitHub token with WRITE access to the repo (the user's own repo / one
  they're authorized on). Read-only scanning is elsewhere; this writes.
- Opens a PR on a NEW branch — never commits to the default branch.
- Defaults to dry-run; the caller must opt in to actually open the PR.
- Only edits text manifests we can rewrite safely (requirements.txt, package.json).
  Lock files are left alone — regenerating them correctly needs the package manager.
"""
import base64
import json
import re
import urllib.error
import urllib.request
from dataclasses import dataclass

GITHUB_API = "https://api.github.com"
EDITABLE = {"requirements.txt", "package.json"}


@dataclass
class Bump:
    file: str
    package: str
    old_version: str
    new_version: str
    ecosystem: str
    advisory: str
    severity: str


def parse_repo(url: str):
    m = re.match(r"https?://github\.com/([^/]+)/([^/]+?)(?:\.git)?/?$", url.strip())
    return (m.group(1), m.group(2)) if m else None


def _norm(name: str) -> str:
    return name.lower().replace("_", "-")


def _vkey(v: str) -> tuple:
    return tuple(int(x) for x in re.findall(r"\d+", v)) or (0,)


def plan_bumps(deps: list) -> list[Bump]:
    """Reduce dependency findings to one bump per (file, package) at the highest fix."""
    best: dict = {}
    for d in deps:
        fname = d.file.replace("\\", "/").rsplit("/", 1)[-1]
        if fname not in EDITABLE or not d.fixed_version:
            continue
        key = (d.file, _norm(d.package))
        cand = Bump(d.file, d.package, d.version, d.fixed_version, d.ecosystem, d.vuln_id, d.severity)
        if key not in best or _vkey(cand.new_version) > _vkey(best[key].new_version):
            best[key] = cand
    return list(best.values())


def _edit_requirements(content: str, bumps: list[Bump]) -> str:
    by_name = {_norm(b.package): b for b in bumps}
    out = []
    for line in content.splitlines():
        stripped = line.strip()
        if stripped.startswith(("#", "-", "git+")) or "://" in stripped:
            out.append(line)
            continue
        m = re.match(r"^(\s*)([A-Za-z0-9][A-Za-z0-9_.\-]*)(\[[^\]]*\])?\s*(.*)$", line)
        if m and _norm(m.group(2)) in by_name:
            b = by_name[_norm(m.group(2))]
            out.append(f"{m.group(1)}{m.group(2)}{m.group(3) or ''}>={b.new_version}")
        else:
            out.append(line)
    text = "\n".join(out)
    return text + "\n" if content.endswith("\n") else text


def _edit_package_json(content: str, bumps: list[Bump]) -> str:
    data = json.loads(content)
    by_name = {b.package: b for b in bumps}
    for section in ("dependencies", "devDependencies"):
        for name in list(data.get(section, {})):
            if name in by_name:
                data[section][name] = f"^{by_name[name].new_version}"
    return json.dumps(data, indent=2) + "\n"


def _apply_edits(path: str, content: str, bumps: list[Bump]) -> str:
    fname = path.replace("\\", "/").rsplit("/", 1)[-1]
    if fname == "requirements.txt":
        return _edit_requirements(content, bumps)
    if fname == "package.json":
        return _edit_package_json(content, bumps)
    return content


def pr_body(bumps: list[Bump]) -> str:
    rows = "\n".join(
        f"| `{b.package}` | {b.old_version} | {b.new_version} | {b.advisory} | {b.severity} |"
        for b in sorted(bumps, key=lambda x: x.package.lower())
    )
    return (
        "## VaultCheck — dependency security fixes\n\n"
        "This PR bumps dependencies with known vulnerabilities to a fixed version.\n\n"
        "| Package | From | To | Advisory | Severity |\n"
        "|---|---|---|---|---|\n"
        f"{rows}\n\n"
        "_Generated by VaultCheck. Review the changes and run your tests before merging._"
    )


def _gh(method: str, path: str, token: str, data=None):
    body = json.dumps(data).encode() if data is not None else None
    req = urllib.request.Request(
        GITHUB_API + path,
        data=body,
        method=method,
        headers={
            "Authorization": f"Bearer {token}",
            "Accept": "application/vnd.github+json",
            "User-Agent": "vaultcheck",
            "Content-Type": "application/json",
        },
    )
    with urllib.request.urlopen(req, timeout=20) as resp:
        return json.loads(resp.read() or "null")


def create_fix_pr(owner: str, repo: str, bumps: list[Bump], token: str,
                  dry_run: bool = True, branch: str = "vaultcheck/dependency-fixes") -> dict:
    by_file: dict = {}
    for b in bumps:
        by_file.setdefault(b.file, []).append(b)

    info = _gh("GET", f"/repos/{owner}/{repo}", token)
    base = info["default_branch"]
    base_sha = _gh("GET", f"/repos/{owner}/{repo}/git/ref/heads/{base}", token)["object"]["sha"]

    changes = []  # (path, new_content, sha)
    for path, file_bumps in by_file.items():
        cur = _gh("GET", f"/repos/{owner}/{repo}/contents/{path}?ref={base}", token)
        content = base64.b64decode(cur["content"]).decode("utf-8", "replace")
        new_content = _apply_edits(path, content, file_bumps)
        if new_content != content:
            changes.append((path, new_content, cur["sha"]))

    body = pr_body(bumps)
    if dry_run:
        return {"dry_run": True, "base": base, "branch": branch,
                "files": [p for p, _, _ in changes], "pr_body": body}

    if not changes:
        return {"dry_run": False, "pr_url": None, "files": [], "note": "Nothing to change."}

    _gh("POST", f"/repos/{owner}/{repo}/git/refs", token,
        {"ref": f"refs/heads/{branch}", "sha": base_sha})
    for path, new_content, sha in changes:
        _gh("PUT", f"/repos/{owner}/{repo}/contents/{path}", token, {
            "message": f"fix(deps): bump vulnerable dependencies in {path}",
            "content": base64.b64encode(new_content.encode()).decode(),
            "sha": sha,
            "branch": branch,
        })
    pr = _gh("POST", f"/repos/{owner}/{repo}/pulls", token,
             {"title": "Fix vulnerable dependencies", "head": branch, "base": base, "body": body})
    return {"dry_run": False, "pr_url": pr.get("html_url"), "files": [p for p, _, _ in changes]}
